### ISSUE TITLE
re-image branch bad image21 DDE selfcal image 

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#64]
Factor crashes because it cannot find any sources in the image (and the mask is empty). For some reason image21 seems to "forget" its calibration. Image21 looks bad, almost like it was made with uncalibrated data? Image11 still looks fine.

(it happened for two different runs so it is not some bad luck that the calibration went wrong...)

This is for the normal DDE selfcalibration cycle, -with- a user provided starting model.

**Comment by rvweeren** [comment]
Some more info. I also get it crashing at the DDE selfcal stage in the same way -without- a user provided skymodel. Now it already fails at image11. Again it seems to be a problem with the masking. (image11 looks bad again, as if no calibration was applied)

2016-04-21 18:03:08 WARNING facetselfcal_facet_patch_539.executable_args: Remote command stderr: --> Opened '/p3600/rvweeren/P214_52_flagged_reimage2block/results/facetselfcal/facet_patch_539/L343226_SBgr025-10_uv.dppp.pre-cal_chunk9_12656E813t_0g.casa_image11.image'
WARNING: FITSFixedWarning: PC01_01 = 1.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: PC02_01 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: PC03_01 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: PC04_01 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: PC01_02 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: PC02_02 = 1.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: PC03_02 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: PC04_02 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: PC01_03 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: PC02_03 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: PC03_03 = 1.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: PC04_03 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: PC01_04 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: PC02_04 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: PC03_04 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: PC04_04 = 1.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
Image size .............................. : (512, 512) pixels
Number of channels ...................... : 1
Number of Stokes parameters ............. : 1
Beam shape (major, minor, pos angle) .... : (2.72067e-03, 1.68762e-03, 80.8) degrees
Frequency of image ...................... : 123.338 MHz
Number of blank pixels .................. : 0 (0.0%)
Flux from sum of (non-blank) pixels ..... : 50.337 Jy
--> Calculating background rms and mean images
--> Using adaptive scaling of rms_box
Using user-specified rms_box ............ : (80, 20) pixels (small scale)
Using user-specified rms_box ............ : (80, 20) pixels (large scale)
--> Using 2D map for background rms
--> Using constant background mean
Min/max values of background rms map .... : (0.13702, 0.88365) Jy/beam
Value of background mean ................ : 0.0 Jy/beam
Minimum number of pixels per island ..... : 9
Number of islands found ................. : 0
--> Grouping Gaussians into sources
Number of sources formed from Gaussians   : 0
--> Opened '/p3600/rvweeren/P214_52_flagged_reimage2block/results/facetselfcal/facet_patch_539/L343226_SBgr025-10_uv.dppp.pre-cal_chunk9_12656E813t_0g.casa_image11.image'
Image size .............................. : (512, 512) pixels
Number of channels ...................... : 1
Number of Stokes parameters ............. : 1
Beam shape (major, minor, pos angle) .... : (2.72067e-03, 1.68762e-03, 80.8) degrees
Frequency of image ...................... : 123.338 MHz
Number of blank pixels .................. : 0 (0.0%)
Flux from sum of (non-blank) pixels ..... : 50.337 Jy
--> Calculating background rms and mean images
--> Using adaptive scaling of rms_box
Using user-specified rms_box ............ : (80, 20) pixels (small scale)
Using user-specified rms_box ............ : (80, 20) pixels (large scale)
--> Using 2D map for background rms
--> Using constant background mean
Min/max values of background rms map .... : (0.13702, 0.88365) Jy/beam
Value of background mean ................ : 0.0 Jy/beam
Minimum number of pixels per island ..... : 9
Number of islands found ................. : 0
--> Grouping Gaussians into sources
Number of sources formed from Gaussians   : 0
--> Opened '/p3600/rvweeren/P214_52_flagged_reimage2block/results/facetselfcal/facet_patch_539/L343226_SBgr025-10_uv.dppp.pre-cal_chunk9_12656E813t_0g.casa_image11.image'
Image size .............................. : (512, 512) pixels
Number of channels ...................... : 1
Number of Stokes parameters ............. : 1
Beam shape (major, minor, pos angle) .... : (2.72067e-03, 1.68762e-03, 80.8) degrees
Frequency of image ...................... : 123.338 MHz
Number of blank pixels .................. : 0 (0.0%)
Flux from sum of (non-blank) pixels ..... : 50.337 Jy
--> Calculating background rms and mean images
--> Using adaptive scaling of rms_box
Using user-specified rms_box ............ : (80, 20) pixels (small scale)
Using user-specified rms_box ............ : (80, 20) pixels (large scale)
--> Using 2D map for background rms
--> Using constant background mean
Min/max values of background rms map .... : (0.13702, 0.88365) Jy/beam
Value of background mean ................ : 0.0 Jy/beam
Minimum number of pixels per island ..... : 9
Number of islands found ................. : 0
--> Grouping Gaussians into sources
Number of sources formed from Gaussians   : 0
--> Opened '/p3600/rvweeren/P214_52_flagged_reimage2block/results/facetselfcal/facet_patch_539/L343226_SBgr025-10_uv.dppp.pre-cal_chunk9_12656E813t_0g.casa_image11.image'
Image size .............................. : (512, 512) pixels
Number of channels ...................... : 1
Number of Stokes parameters ............. : 1
Beam shape (major, minor, pos angle) .... : (2.72067e-03, 1.68762e-03, 80.8) degrees
Frequency of image ...................... : 123.338 MHz
Number of blank pixels .................. : 0 (0.0%)
Flux from sum of (non-blank) pixels ..... : 50.337 Jy
--> Calculating background rms and mean images
--> Using adaptive scaling of rms_box
Using user-specified rms_box ............ : (80, 20) pixels (small scale)
Using user-specified rms_box ............ : (80, 20) pixels (large scale)
--> Using 2D map for background rms
--> Using constant background mean
Min/max values of background rms map .... : (0.13702, 0.88365) Jy/beam
Value of background mean ................ : 0.0 Jy/beam
Minimum number of pixels per island ..... : 9
Number of islands found ................. : 0
--> Grouping Gaussians into sources
Number of sources formed from Gaussians   : 0
--> Opened '/p3600/rvweeren/P214_52_flagged_reimage2block/results/facetselfcal/facet_patch_539/L343226_SBgr025-10_uv.dppp.pre-cal_chunk9_12656E813t_0g.casa_image11.image'
Image size .............................. : (512, 512) pixels
Number of channels ...................... : 1
Number of Stokes parameters ............. : 1
Beam shape (major, minor, pos angle) .... : (2.72067e-03, 1.68762e-03, 80.8) degrees
Frequency of image ...................... : 123.338 MHz
Number of blank pixels .................. : 0 (0.0%)
Flux from sum of (non-blank) pixels ..... : 50.337 Jy
--> Calculating background rms and mean images
--> Using adaptive scaling of rms_box
Using user-specified rms_box ............ : (80, 20) pixels (small scale)
Using user-specified rms_box ............ : (80, 20) pixels (large scale)
--> Using 2D map for background rms
--> Using constant background mean
Min/max values of background rms map .... : (0.13702, 0.88365) Jy/beam
Value of background mean ................ : 0.0 Jy/beam
Minimum number of pixels per island ..... : 9
Number of islands found ................. : 0
--> Grouping Gaussians into sources
Number of sources formed from Gaussians   : 0
--> Opened '/p3600/rvweeren/P214_52_flagged_reimage2block/results/facetselfcal/facet_patch_539/L343226_SBgr025-10_uv.dppp.pre-cal_chunk9_12656E813t_0g.casa_image11.image'
Image size .............................. : (512, 512) pixels
Number of channels ...................... : 1
Number of Stokes parameters ............. : 1
Beam shape (major, minor, pos angle) .... : (2.72067e-03, 1.68762e-03, 80.8) degrees
Frequency of image ...................... : 123.338 MHz
Number of blank pixels .................. : 0 (0.0%)
Flux from sum of (non-blank) pixels ..... : 50.337 Jy
--> Calculating background rms and mean images
--> Using adaptive scaling of rms_box
Using user-specified rms_box ............ : (80, 20) pixels (small scale)
Using user-specified rms_box ............ : (80, 20) pixels (large scale)
--> Using 2D map for background rms
--> Using constant background mean
Min/max values of background rms map .... : (0.13702, 0.88365) Jy/beam
Value of background mean ................ : 0.0 Jy/beam
Minimum number of pixels per island ..... : 9
Number of islands found ................. : 0
--> Grouping Gaussians into sources
Number of sources formed from Gaussians   : 0
--> Opened '/p3600/rvweeren/P214_52_flagged_reimage2block/results/facetselfcal/facet_patch_539/L343226_SBgr025-10_uv.dppp.pre-cal_chunk9_12656E813t_0g.casa_image11.image'
Image size .............................. : (512, 512) pixels
Number of channels ...................... : 1
Number of Stokes parameters ............. : 1
Beam shape (major, minor, pos angle) .... : (2.72067e-03, 1.68762e-03, 80.8) degrees
Frequency of image ...................... : 123.338 MHz
Number of blank pixels .................. : 0 (0.0%)
Flux from sum of (non-blank) pixels ..... : 50.337 Jy
--> Calculating background rms and mean images
--> Using adaptive scaling of rms_box
Using user-specified rms_box ............ : (80, 20) pixels (small scale)
Using user-specified rms_box ............ : (80, 20) pixels (large scale)
--> Using 2D map for background rms
--> Using constant background mean
Min/max values of background rms map .... : (0.13702, 0.88365) Jy/beam
Value of background mean ................ : 0.0 Jy/beam
Minimum number of pixels per island ..... : 9
Number of islands found ................. : 0
--> Grouping Gaussians into sources
Number of sources formed from Gaussians   : 0

2016-04-21 18:03:08 ERROR   facetselfcal_facet_patch_539.executable_args: Remote process python /home/rvweeren/software/lofarapr2016/opt/LofIm/lib/python2.7/site-packages/lofarpipe/recipes/nodes/python_plugin.py ['/p3600/rvweeren/P214_52_flagged_reimage2block/results/facetselfcal/facet_patch_539/L343226_SBgr025-10_uv.dppp.pre-cal_chunk9_12656E813t_0g.casa_image11.image', '/usr/local/lib/python2.7/dist-packages/FACTOR-1.0-py2.7.egg/factor/scripts/make_clean_mask.py', ['/p3600/rvweeren/P214_52_flagged_reimage2block/results/facetselfcal/facet_patch_539/L343226_SBgr025-10_uv.dppp.pre-cal_chunk9_12656E813t_0g.casa_image11.image', '/p3600/rvweeren/P214_52_flagged_reimage2block/results/facetselfcal/facet_patch_539/L343226_SBgr025-10_uv.dppp.pre-cal_chunk9_12656E813t_0g.casa_image11.mask1'], {'threshpix': '15', 'adaptive_rmsbox': 'True', 'trim_by': '0.2', 'atrous_do': 'False', 'threshisl': '15', 'iterate_threshold': 'True', 'region_file': '[]', 'rmsbox': '(80,20)', 'threshold_format': 'str_with_units', 'img_format': 'casa'}, '/p3600/rvweeren/P214_52_flagged_reimage2block/results/facetselfcal/facet_patch_539', False, {'args_format_option_argument': '=', 'args_format_option': '-', 'args_format': 'gnu', 'args_formatlongoption': '--', 'args_format_argument': ''}, {'SHLIB_PATH': '/home/rvweeren/software/root/lib:', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 'LOFARDATAROOT': '/opt/lofar/data', 'PYTHONPATH': '/home/rvweeren/software/lofarapr2016/opt/LofIm/lib/python2.7/site-packages:/home/rvweeren/software/root/lib:/home/rvweeren/software/heasoft-6.16/x86_64-unknown-linux-gnu-libc2.19-0/lib/python:/home/rvweeren/software/heasoft-6.16/x86_64-unknown-linux-gnu-libc2.19-0/lib:/home/rvweeren/software/wcsaxes/build/lib/python/:/home/rvweeren/software/pyvo/build/lib/python/:/home/rvweeren/software/wcsaxes/build/lib/python/:/home/rvweeren/software/pyvo/build/lib/python/:/home/rvweeren/software/wcsaxes/build/lib/python/:/home/rvweeren/software/pyvo/build/lib/python/::/home/rvweeren/scripts/pp:/home/rvweeren/scripts/pp:/home/rvweeren/scripts/pp', 'COMPIZ_BIN_PATH': '/usr/bin/', 'LIBPATH': '/home/rvweeren/software/root/lib:', 'DYLD_LIBRARY_PATH': '/home/rvweeren/software/root/lib:', 'LOFARROOT': '/home/rvweeren/software/lofarapr2016/opt/LofIm', 'MANPATH': '/home/rvweeren/software/root/man:/home/rvweeren/software/heasoft-6.16/x86_64-unknown-linux-gnu-libc2.19-0/man:/usr/local/man:/usr/local/share/man:/usr/share/man', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'PATH': '/home/rvweeren/software/lofarapr2016/opt/LofIm/bin:/home/rvweeren/software/lofarapr2016/opt/LofIm/sbin:/home/rvweeren/software/root/bin:/home/rvweeren/software/heasoft-6.16/x86_64-unknown-linux-gnu-libc2.19-0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/rvweeren/software/casapy/casa-release-4.6.0-el6/bin:/home/rvweeren/software/WSClean/wsclean-1.11b/build/:/home/rvweeren/software/ds9/:/home/rvweeren/software/UDR/src/:/home/rvweeren/software/losoto:/home/rvweeren/software/losoto/tools:/home/rvweeren/software/casapy/casa-release-4.6.0-el6:/home/rvweeren/software/WSClean/wsclean-1.11b/build/:/home/rvweeren/software/ds9/:/home/rvweeren/software/UDR/src/:/home/rvweeren/software/losoto:/home/rvweeren/software/losoto/tools:/home/rvweeren/software/casapy/casa-release-4.6.0-el6:/home/rvweeren/software/WSClean/wsclean-1.11b/build/:/home/rvweeren/software/ds9/:/home/rvweeren/software/UDR/src/:/home/rvweeren/software/losoto:/home/rvweeren/software/losoto/tools', 'LD_LIBRARY_PATH': '/home/rvweeren/software/lofarapr2016/opt/LofIm/lib:/home/rvweeren/software/root/lib:/home/rvweeren/software/heasoft-6.16/x86_64-unknown-linux-gnu-libc2.19-0/lib'}] failed on localhost (status: 1)
2016-04-21 18:03:08 DEBUG   facetselfcal_facet_patch_539.executable_args: compute.dispatch results job 0: job_duration: 13.0286679268, returncode: 1 
2016-04-21 18:03:09 DEBUG   facetselfcal_facet_patch_539.executable_args: Adding node_logging_information
2016-04-21 18:03:09 ERROR   facetselfcal_facet_patch_539.executable_args: A job has failed and error_tolerance is not set. Bailing out!
2016-04-21 18:03:09 WARNING facetselfcal_facet_patch_539.executable_args: Note: recipe outputs are not complete
2016-04-21 18:03:09 WARNING facetselfcal_facet_patch_539.executable_args: recipe executable_args completed with errors
2016-04-21 18:03:09 WARNING facetselfcal_facet_patch_539: make_clean_mask reports failure (using executable_args recipe)
2016-04-21 18:03:09 ERROR   facetselfcal_facet_patch_539: *******************************************
2016-04-21 18:03:09 ERROR   facetselfcal_facet_patch_539: Failed pipeline run: facet_patch_539
2016-04-21 18:03:09 ERROR   facetselfcal_facet_patch_539: Detailed exception information:
2016-04-21 18:03:09 ERROR   facetselfcal_facet_patch_539: <class 'lofarpipe.support.lofarexceptions.PipelineRecipeFailed'>
2016-04-21 18:03:09 ERROR   facetselfcal_facet_patch_539: make_clean_mask failed
2016-04-21 18:03:09 ERROR   facetselfcal_facet_patch_539: *******************************************
2016-04-21 18:03:09 ERROR   facetselfcal_facet_patch_539: LOFAR Pipeline finished unsuccesfully.
2016-04-21 18:03:09 WARNING facetselfcal_facet_patch_539: recipe facetselfcal_facet_patch_539 completed with errors

**Comment by darafferty** [comment]
Are you using the new clean threshold option? That is, could it be that the images are bad because they were not cleaned deeply enough?

**Comment by rvweeren** [comment]
No that is not the reason. No calibration is applied it seems as there hardly is a source visible. 

(and selfcal_clean_threshold was -not- set)

**Comment by darafferty** [comment]
What does the mask look like for the image previous to calibration that produces the bad image (e.g., image02 in the case where image11 was bad). Maybe the masking goes wrong there and it calibrates somehow on empty model data? Can you also check the casa logs for the various imaging and ft runs? The pipeline doesn't realize when casapy fails (during ft, for example) and just continues on obliviously.

**Comment by darafferty** [comment]
By the way, the casa logs are in the tmp directories inside the facetselfcal directory of the facet.

**Comment by rvweeren** [comment]
image02 mask looks ok.

**Comment by rvweeren** [comment]
Ok it's the FFT failure. I switched to casapy 4.6. That explains my problems.

---

```
For help use the following commands:
tasklist               - Task list organized by category
taskhelp               - One line summary of available tasks
help taskname          - Full help for task
toolhelp               - One line summary of available tools
help par.parametername - Full help for parameter name
```

---

will execute script /usr/local/lib/python2.7/dist-packages/FACTOR-1.0-py2.7.egg/factor/scripts/do_ft.py
Activating auto-logging. Current session state plus future input saved.
Filename       : ipython-20160421-220118.log
Mode           : backup
Output logging : False
Raw input log  : False
Timestamping   : False
State          : active
**\* Loading ATNF ASAP Package...

## **\* ... ASAP (rev#36500) import complete ***

ImportError                               Traceback (most recent call last)

/home/rvweeren/software/casapy/casa-release-4.6.0-el6/lib/python2.7/casapy.py in <module>()
----> 1 
      2 
      3 
      4 
      5 

/home/rvweeren/software/casapy/casa-release-4.6.0-el6/lib/python2.7/casapy.py in <module>()
     27     del os.environ['INSTALLDIR']
     28 os.system('buildmytasks')
---> 29 execfile('mytasks.py')
     30 
     31 ms    = sys.argv[5]

/home/rvweeren/software/casapy/casa-release-4.6.0-el6/lib/python2.7/casapy.py in <module>()
     22   tasksum[key] = mytasks[key]

```
 23 
```

---> 24 from ftw_cli import  ftw_cli as ftw
     25 
     26 

ImportError: cannot import name ftw_cli
leaving casapy...

**Comment by darafferty** [comment]
Ah. Darn casapy...

**Comment by rvweeren** [comment]
Is it possible to pass the full path of buildmytasks ?

(because I checked and buildmytasks is the problem, the FFT itself works in casapy 4.6)

If I use buildmytasks from casapy 4.5 I can successfully do the FFT in 4.6. So if there is an option to specify the full path to buildmytasks the problem should be fixed.

**Comment by nudomarinero** [comment]
Which versions of casapy work well? I know 4.2 and 4.5 work (don't they?). According to this thread 4.6 has a problem with buildmytasks. Does 4.4 work as well?

**Comment by rvweeren** [comment]
4.2.2 and 4.5 work (4.3 and 4.4 are not working if I am correct)

4.6 almost works, just a problem with buildmytasks (ft/clean both work). I notified the NRAO helpdesk about this so hopefully they fix it.

**Comment by darafferty** [comment]
It's not possible to specify the path to buildmytasks, but I can add it easily. Factor just assumes it's in your $PATH, so if you can alter that to pick up only the old version it should work.

**Comment by darafferty** [comment]
As far as I know, too, 4.3 and 4.4 don't work.

**Comment by rvweeren** [comment]
For now I switched back to 4.5.2. Let's see if the NRAO people fix this soon then we do not have to take action. We should add a warning that Factor is not 4.6 compatible at the moment.

FYI:  For casapy 4.6+, they will change the name of the executable from casapy to casa. (they already start throwing warnings at you when you start with "casapy" instead of "casa" in version 4.6, and they will remove "casapy" in 4.7).

(For now) I will close this issue.
